service: hello-world

provider:
    runtime: nodejs8.10
    name: aws
    stage: dev
    region: ap-northeast-2

functions:
    main:
        handler: out/ex-001/Handler.hello
        events:
            - http:
                  path: /
                  method: get
                  cors: true

plugins:
    - serverless-offline
