export class Profile {
    public id: number;
    public name: string;

    constructor(id: number, name: string) {
        this.id = id;
        this.name = name;
    }

    public base64(): string {
        return Buffer.from(this.id.toString(), "binary").toString("base64");
    }
}

export let data = new Array<Profile>();
data.push(new Profile(0, "가렌"));
data.push(new Profile(1, "갈리오"));
data.push(new Profile(2, "갱플랭크"));
data.push(new Profile(3, "그라가스"));
data.push(new Profile(4, "그레이브즈"));
data.push(new Profile(5, "나르"));
data.push(new Profile(6, "나미"));
data.push(new Profile(7, "나서스"));
data.push(new Profile(8, "노틸러스"));
data.push(new Profile(9, "녹턴"));
data.push(new Profile(10, "누누와 윌럼프"));
data.push(new Profile(11, "니달리"));
data.push(new Profile(12, "니코"));
data.push(new Profile(13, "다리우스"));
data.push(new Profile(14, "다이애나"));
data.push(new Profile(15, "드레이븐"));
data.push(new Profile(16, "라이즈"));
data.push(new Profile(17, "라칸"));
data.push(new Profile(18, "람머스"));
data.push(new Profile(19, "럭스"));
data.push(new Profile(20, "럼블"));
data.push(new Profile(21, "레넥톤"));
data.push(new Profile(22, "레오나"));
data.push(new Profile(23, "렉사이"));
data.push(new Profile(24, "렝가"));
data.push(new Profile(25, "루시안"));
data.push(new Profile(26, "룰루"));
data.push(new Profile(27, "르블랑"));
data.push(new Profile(28, "리 신"));
data.push(new Profile(29, "리븐"));
data.push(new Profile(30, "리산드라"));
data.push(new Profile(31, "마스터 이"));
data.push(new Profile(32, "마오카이"));
data.push(new Profile(33, "말자하"));
data.push(new Profile(34, "말파이트"));
data.push(new Profile(35, "모데카이저"));
data.push(new Profile(36, "모르가나"));
data.push(new Profile(37, "문도 박사"));
data.push(new Profile(38, "미스 포츈"));
data.push(new Profile(39, "바드"));
data.push(new Profile(40, "바루스"));
data.push(new Profile(41, "바이"));
data.push(new Profile(42, "베이가"));
data.push(new Profile(43, "베인"));
data.push(new Profile(44, "벨코즈"));
data.push(new Profile(45, "볼리베어"));
data.push(new Profile(46, "브라움"));
data.push(new Profile(47, "브랜드"));
data.push(new Profile(48, "블라디미르"));
data.push(new Profile(49, "블리츠크랭크"));
data.push(new Profile(50, "빅토르"));
data.push(new Profile(51, "뽀삐"));
data.push(new Profile(52, "사이온"));
data.push(new Profile(53, "사일러스"));
data.push(new Profile(54, "샤코"));
data.push(new Profile(55, "세나"));
data.push(new Profile(56, "세주아니"));
data.push(new Profile(57, "소나"));
data.push(new Profile(58, "소라카"));
data.push(new Profile(59, "쉔"));
data.push(new Profile(60, "쉬바나"));
data.push(new Profile(61, "스웨인"));
data.push(new Profile(62, "스카너"));
data.push(new Profile(63, "시비르"));
data.push(new Profile(64, "신 짜오"));
data.push(new Profile(65, "신드라"));
data.push(new Profile(66, "신지드"));
data.push(new Profile(67, "쓰레쉬"));
data.push(new Profile(68, "아리"));
data.push(new Profile(69, "아무무"));
data.push(new Profile(70, "아우렐리온 솔"));
data.push(new Profile(71, "아이번"));
data.push(new Profile(72, "아지르"));
data.push(new Profile(73, "아칼리"));
data.push(new Profile(74, "아트록스"));
data.push(new Profile(75, "아펠리오스"));
data.push(new Profile(76, "알리스타"));
data.push(new Profile(77, "애니"));
data.push(new Profile(78, "애니비아"));
data.push(new Profile(79, "애쉬"));
data.push(new Profile(80, "야스오"));
data.push(new Profile(81, "에코"));
data.push(new Profile(82, "엘리스"));
data.push(new Profile(83, "오공"));
data.push(new Profile(84, "오른"));
data.push(new Profile(85, "오리아나"));
data.push(new Profile(86, "올라프"));
data.push(new Profile(87, "요릭"));
data.push(new Profile(88, "우디르"));
data.push(new Profile(89, "우르곳"));
data.push(new Profile(90, "워윅"));
data.push(new Profile(91, "유미"));
data.push(new Profile(92, "이렐리아"));
data.push(new Profile(93, "이블린"));
data.push(new Profile(94, "이즈리얼"));
data.push(new Profile(95, "일라오이"));
data.push(new Profile(96, "자르반 4세"));
data.push(new Profile(97, "자야"));
data.push(new Profile(98, "자이라"));
data.push(new Profile(99, "자크"));
data.push(new Profile(100, "잔나"));
data.push(new Profile(101, "잭스"));
data.push(new Profile(102, "제드"));
data.push(new Profile(103, "제라스"));
data.push(new Profile(104, "제이스"));
data.push(new Profile(105, "조이"));
data.push(new Profile(106, "직스"));
data.push(new Profile(107, "진"));
data.push(new Profile(108, "질리언"));
data.push(new Profile(109, "징크스"));
data.push(new Profile(110, "초가스"));
data.push(new Profile(111, "카르마"));
data.push(new Profile(112, "카밀"));
data.push(new Profile(113, "카사딘"));
data.push(new Profile(114, "카서스"));
data.push(new Profile(115, "카시오페아"));
data.push(new Profile(116, "카이사"));
data.push(new Profile(117, "카직스"));
data.push(new Profile(118, "카타리나"));
data.push(new Profile(119, "칼리스타"));
data.push(new Profile(120, "케넨"));
data.push(new Profile(121, "케이틀린"));
data.push(new Profile(122, "케인"));
data.push(new Profile(123, "케일"));
data.push(new Profile(124, "코그모"));
data.push(new Profile(125, "코르키"));
data.push(new Profile(126, "퀸"));
data.push(new Profile(127, "클레드"));
data.push(new Profile(128, "키아나"));
data.push(new Profile(129, "킨드레드"));
data.push(new Profile(130, "타릭"));
data.push(new Profile(131, "탈론"));
data.push(new Profile(132, "탈리야"));
data.push(new Profile(133, "탐 켄치"));
data.push(new Profile(134, "트런들"));
data.push(new Profile(135, "트리스타나"));
data.push(new Profile(136, "트린다미어"));
data.push(new Profile(137, "트위스티드 페이트"));
data.push(new Profile(138, "트위치"));
data.push(new Profile(139, "티모"));
data.push(new Profile(140, "파이크"));
data.push(new Profile(141, "판테온"));
data.push(new Profile(142, "피들스틱"));
data.push(new Profile(143, "피오라"));
data.push(new Profile(144, "피즈"));
data.push(new Profile(145, "하이머딩거"));
data.push(new Profile(146, "헤카림"));
