service: hello-world

provider:
    runtime: nodejs8.10
    name: aws
    stage: dev
    region: ap-northeast-2

functions:
    main:
        handler: out/chapter-04-expressApollo/001-start/Lambda.handler
        events:
            - http:
                  path: /
                  method: any
                  cors: true

plugins:
    - serverless-offline
