const loremIpsum: string[] = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "Sed nisi lacus sed viverra tellus in hac.",
    "Varius quam quisque id diam vel quam elementum pulvinar etiam.",
    "Nisl condimentum id venenatis a condimentum.",
    "Volutpat odio facilisis mauris sit amet massa.",
    "Arcu dictum varius duis at consectetur lorem.",
    "Enim eu turpis egestas pretium aenean.",
    "Odio euismod lacinia at quis risus.",
    "Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus.",
    "Phasellus vestibulum lorem sed risus.",
    "Maecenas ultricies mi eget mauris.",
    "In nisl nisi scelerisque eu ultrices.",
    "Cursus turpis massa tincidunt dui ut ornare lectus.",
    "Id aliquet lectus proin nibh nisl condimentum id venenatis.",
    "Magna fermentum iaculis eu non diam phasellus vestibulum lorem.",
    "Posuere morbi leo urna molestie at.",
    "Ac tortor vitae purus faucibus ornare.",
    "Sodales ut etiam sit amet nisl purus in.",
    "Amet dictum sit amet justo.",
    "Lacus laoreet non curabitur gravida arcu ac tortor.",
    "Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique.",
    "Mattis ullamcorper velit sed ullamcorper.",
    "Ut sem nulla pharetra diam sit amet nisl suscipit adipiscing.",
    "Tortor dignissim convallis aenean et tortor at risus viverra adipiscing.",
    "Sed id semper risus in hendrerit gravida rutrum quisque.",
    "Vel eros donec ac odio tempor.",
    "Pharetra diam sit amet nisl suscipit adipiscing bibendum est.",
    "Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus.",
    "Pellentesque elit eget gravida cum sociis natoque penatibus.",
    "Tortor dignissim convallis aenean et.",
    "Massa sed elementum tempus egestas sed sed risus.",
    "Urna id volutpat lacus laoreet non.",
    "At augue eget arcu dictum varius duis at consectetur.",
    "Lectus magna fringilla urna porttitor rhoncus dolor.",
    "Urna neque viverra justo nec ultrices.",
    "Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat.",
    "Euismod in pellentesque massa placerat duis ultricies.",
    "Molestie ac feugiat sed lectus vestibulum mattis.",
    "Tortor posuere ac ut consequat.",
    "Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac.",
    "Tincidunt vitae semper quis lectus nulla at volutpat diam ut.",
    "Massa eget egestas purus viverra accumsan in nisl.",
    "Elementum curabitur vitae nunc sed.",
    "Id neque aliquam vestibulum morbi blandit.",
    "Malesuada fames ac turpis egestas maecenas.",
    "Imperdiet proin fermentum leo vel orci.",
    "Ullamcorper eget nulla facilisi etiam dignissim diam quis enim.",
    "Quisque id diam vel quam elementum pulvinar etiam non quam.",
    "Purus non enim praesent elementum.",
    "Ullamcorper velit sed ullamcorper morbi tincidunt.",
    "A cras semper auctor neque.",
    "A scelerisque purus semper eget duis.",
    "Sagittis orci a scelerisque purus semper eget.",
    "Lorem donec massa sapien faucibus et molestie ac.",
    "Sit amet facilisis magna etiam tempor orci eu.",
    "Fermentum et sollicitudin ac orci phasellus.",
    "Orci ac auctor augue mauris.",
    "Venenatis cras sed felis eget.",
    "Ultricies lacus sed turpis tincidunt id aliquet risus.",
    "Et netus et malesuada fames ac turpis egestas integer.",
    "Ut eu sem integer vitae justo eget.",
    "Dui id ornare arcu odio ut.",
    "Commodo nulla facilisi nullam vehicula ipsum a.",
    "Vitae turpis massa sed elementum tempus egestas.",
    "Placerat vestibulum lectus mauris ultrices eros.",
    "Felis bibendum ut tristique et egestas quis ipsum suspendisse.",
    "Elit ullamcorper dignissim cras tincidunt lobortis.",
    "Risus viverra adipiscing at in.",
    "Id eu nisl nunc mi ipsum faucibus vitae.",
    "Sit amet consectetur adipiscing elit ut aliquam purus.",
    "Nunc sed velit dignissim sodales ut eu sem.",
    "Enim nunc faucibus a pellentesque.",
    "Vel risus commodo viverra maecenas accumsan lacus.",
    "Elementum nibh tellus molestie nunc non blandit massa enim.",
    "Aliquam purus sit amet luctus venenatis lectus magna fringilla.",
    "Eget aliquet nibh praesent tristique magna sit.",
    "Duis at consectetur lorem donec massa sapien.",
    "Scelerisque fermentum dui faucibus in ornare quam viverra.",
    "Faucibus scelerisque eleifend donec pretium vulputate sapien.",
    "Mauris nunc congue nisi vitae suscipit tellus mauris a.",
    "Vitae suscipit tellus mauris a.",
    "Consequat id porta nibh venenatis cras sed felis.",
    "Id aliquet lectus proin nibh nisl.",
    "Maecenas sed enim ut sem viverra aliquet eget.",
    "Scelerisque eleifend donec pretium vulputate sapien.",
    "Arcu risus quis varius quam.",
    "Faucibus pulvinar elementum integer enim neque.",
    "Eu ultrices vitae auctor eu augue ut.",
    "Nunc lobortis mattis aliquam faucibus purus in massa.",
    "Mattis enim ut tellus elementum sagittis vitae.",
    "Id ornare arcu odio ut sem nulla.",
    "A erat nam at lectus urna duis convallis.",
    "Dolor magna eget est lorem ipsum dolor sit amet.",
    "In arcu cursus euismod quis viverra nibh cras pulvinar mattis.",
    "Adipiscing diam donec adipiscing tristique risus nec feugiat in.",
    "Malesuada pellentesque elit eget gravida.",
    "Fermentum et sollicitudin ac orci phasellus egestas.",
    "Neque volutpat ac tincidunt vitae semper quis.",
    "Arcu vitae elementum curabitur vitae nunc sed.",
    "Sit amet luctus venenatis lectus magna fringilla urna."
];
export default loremIpsum;
