service: hello-world

provider:
    runtime: nodejs8.10
    name: aws
    stage: dev
    region: ap-northeast-2

functions:
    main:
        handler: out/ex-007/Lambda.handler
        events:
            - http:
                  path: /{any+}
                  method: any
                  cors: true
plugins:
    - serverless-offline
